# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
    push:
        branches: [master, next, beta, alpha]
    pull_request:
        branches: [master, next, beta, alpha]

permissions:
    packages: write
    contents: write
    issues: write
    pull-requests: write

jobs:
    build:

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v3

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install
              run: |
                npm ci

            - name: Build
              run: |
                npm run build

            - name: Release
              id: semantic
              uses: cycjimmy/semantic-release-action@v3
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
              with:
                  extra_plugins: |
                      @semantic-release/changelog
                      @semantic-release/git
